### ISSUE TITLE
Not able to access http://pluto.studio. It is simply processing and the page is not loading.

### ISSUE THREAD

**Issue by Aditi820** [shyams80/pluto#3]

**Comment by Aditi820** [comment]
![Error_Pluto](https://user-images.githubusercontent.com/16935610/63207845-eba74900-c0ea-11e9-922e-e11fe9332c7e.png)

**Comment by shyams80** [comment]
A new release was being pushed out. Changes listed [here](https://github.com/shyams80/pluto/releases/tag/v0.0.1)

To access JupyterHub notebooks like before, go to [http://**app.** pluto.studio](http://app.pluto.studio).

If you are still facing issues, try steps outlined [here](https://github.com/shyams80/pluto/issues/1#issuecomment-519087948)
